name = "netutils"
version = "1.0.0"
description = "Network utilities (ping, telnet, curl, etc.) for BoredOS"
author = "Christiaan"
license = "GPLv3"

[install]
bin = "/bin"
config = "/Library/Certificates"
assets = "/Library/AppData/org.boredos.httpd"
